# This github action flow is used for releasing a new vNext version before an official release is done.
# In this flow we update the docs, but we could also release an alpha version of the packages (if needed - depends on cleanup on nexus registry)
# Currently we don't do that. Code is put in comments however at the bottom.

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #needed for retrieving all tags

      # retrieve current latest tag
      - name: Get latest Git Tag
        id: get-latest-tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      # Use the value of LATEST_TAG
      - name: Use LATEST_TAG
        run: echo $LATEST_TAG

      # Get how many commits are after the latest tag
      - name: Get number of commits after last tag
        id: commits-after-tag
        run: echo "COMMITS_AFTER_TAG=$(git rev-list ${{env.LATEST_TAG}}..HEAD --count)" >> $GITHUB_ENV

      - name: Print output
        run: echo "version ${{env.LATEST_TAG}}-alpha-${{env.COMMITS_AFTER_TAG}}"

      # TODO: extract the v from the latest tag

      # Release alpha packages (numbering: latestTag-numberOfCommits. for example: 1.2.0-alpha-5)
      # - name: deploy alpha packages
      #  run: node tools/release-alpha.js --version=${{steps.get-latest-tag.outputs.latest-tag}}-alpha-${{steps.commits-after-tag.outputs.commits-after-tag}}
